xcodebuild_arguments:
  - -scheme
  - SRP
module: SRP
author: Bouke Haarsma
author_url: https://twitter.com/BoukeHaarsma
output: ../SRP-Docs/master
theme: fullwidth
clean: true
github_url: https://github.com/Bouke/SRP
dash_url: http://boukehaarsma.nl/SRP/SRP.xml
